"""Experimento reproducible que construye las muestras de la tesis."""

from .comparacion_generadores import (
    LAGS_COMPARACION,
    MALLA_CDF,
    MALLA_FC,
    MALLA_FGM,
    ORDEN_MAXIMO_MOMENTOS_COMPARACION,
    construir_comparacion_generadores,
    construir_muestras_comparacion,
)
from .muestras import (
    construir_muestras,
    muestra_logistica,
    muestra_tienda,
    muestras_regla_30,
)
from .invariancia import (
    ITERACIONES_INVARIANCIA,
    NUM_PARTICULAS_INVARIANCIA,
    SEED_INVARIANCIA,
    aplicar_logistico,
    aplicar_tienda,
    construir_experimentos_invariancia,
    evolucion_ensemble,
    muestra_inicial_logistica,
    muestra_inicial_tienda,
)
from .parametros import (
    FACTOR_TIENDA,
    INTERVALOS_BRECHAS_COMUNES,
    LONGITUD_INTERVALO_BRECHAS,
    NUM_CELDAS,
    NUM_ITERACIONES,
    NUM_VALORES,
    PROBABILIDAD_BRECHAS,
    SEED,
    SEED_MINSTD,
    SEED_REORDENAMIENTO,
    validar_intervalos_brechas_comunes,
)
from .reordenamiento import (
    LAGS_REORDENAMIENTO,
    construir_experimentos_reordenamiento,
    construir_permutaciones_reordenamiento,
    fingerprint_permutacion,
)
from .soportes_coleccionista import (
    MUESTRAS_COLECCIONISTA,
    calcular_maximo_soporte_coleccionista_comun,
    construir_participantes_malla_coleccionista,
)

__all__ = (
    "LAGS_COMPARACION",
    "MALLA_CDF",
    "MALLA_FC",
    "MALLA_FGM",
    "ORDEN_MAXIMO_MOMENTOS_COMPARACION",
    "SEED_MINSTD",
    "construir_comparacion_generadores",
    "construir_muestras_comparacion",
    "FACTOR_TIENDA",
    "INTERVALOS_BRECHAS_COMUNES",
    "LONGITUD_INTERVALO_BRECHAS",
    "NUM_CELDAS",
    "NUM_ITERACIONES",
    "NUM_VALORES",
    "PROBABILIDAD_BRECHAS",
    "SEED",
    "SEED_MINSTD",
    "SEED_REORDENAMIENTO",
    "validar_intervalos_brechas_comunes",
    "ITERACIONES_INVARIANCIA",
    "NUM_PARTICULAS_INVARIANCIA",
    "SEED_INVARIANCIA",
    "aplicar_logistico",
    "aplicar_tienda",
    "construir_experimentos_invariancia",
    "evolucion_ensemble",
    "muestra_inicial_logistica",
    "muestra_inicial_tienda",
    "construir_muestras",
    "muestra_logistica",
    "muestra_tienda",
    "muestras_regla_30",
    "LAGS_REORDENAMIENTO",
    "SEED_REORDENAMIENTO",
    "construir_experimentos_reordenamiento",
    "construir_permutaciones_reordenamiento",
    "fingerprint_permutacion",
    "MUESTRAS_COLECCIONISTA",
    "calcular_maximo_soporte_coleccionista_comun",
    "construir_participantes_malla_coleccionista",
)
