"""Visualización reproducible de los experimentos de la tesis."""

from .coleccionista import (
    ETIQUETAS,
    NOMBRES_FIGURAS,
    guardar_cdf,
    guardar_pmf,
    rango_grafica,
    regenerar,
    regenerar_muestra,
    validar_muestra,
)
from .momentos import (
    ARCHIVOS_REFERENCIA,
    ARCHIVOS_TESIS,
    N_HISTOGRAMAS,
    NUM_BINS_HISTOGRAMAS,
    ORDEN_MAXIMO_LOGISTICO,
    ORDEN_MAXIMO_OTROS,
    SEED_HISTOGRAMAS,
    VENTANA_HISTOGRAMAS,
    bordes_histogramas,
    calcular_histograma,
    copiar_referencias,
    generar_muestras_histogramas,
    regenerar_momentos,
)
from .transformadas import (
    ARCHIVOS_REFERENCIA_TRANSFORMADAS,
    ARCHIVOS_TESIS_TRANSFORMADAS,
    T_FC,
    T_FGM,
    copiar_referencias_transformadas,
    regenerar_transformadas,
)

__all__ = (
    "ETIQUETAS",
    "NOMBRES_FIGURAS",
    "guardar_cdf",
    "guardar_pmf",
    "rango_grafica",
    "regenerar",
    "regenerar_muestra",
    "validar_muestra",
    "ARCHIVOS_REFERENCIA",
    "ARCHIVOS_TESIS",
    "N_HISTOGRAMAS",
    "NUM_BINS_HISTOGRAMAS",
    "ORDEN_MAXIMO_LOGISTICO",
    "ORDEN_MAXIMO_OTROS",
    "SEED_HISTOGRAMAS",
    "VENTANA_HISTOGRAMAS",
    "bordes_histogramas",
    "calcular_histograma",
    "copiar_referencias",
    "generar_muestras_histogramas",
    "regenerar_momentos",
    "ARCHIVOS_REFERENCIA_TRANSFORMADAS",
    "ARCHIVOS_TESIS_TRANSFORMADAS",
    "T_FC",
    "T_FGM",
    "copiar_referencias_transformadas",
    "regenerar_transformadas",
)
